# @mason: flutter_rust_bridge

# When 'just' is called with no arguments,
# these recipes are run by default.

default: check lint

# Add new recipes to these meta-recipes as you add new modules.

lint: lint_metronome
clean: clean_metronome
    flutter clean
check: check_metronome
    flutter analyze

alias c := check
alias l := lint


# Recipes for metronome

lint_metronome:
    cd metronome && cargo fmt
    cd metronome && dart format --line-length 80
clean_metronome:
    cd metronome && cargo clean
check_metronome:
    cd metronome && cargo check
