name: flutter_metronome
description: A Metronome built in Flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.0
  soundpool: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - packages/flutter_metronome/assets/metronome_electric_up.wav
    - packages/flutter_metronome/assets/metronome_electric.wav
    - packages/flutter_metronome/images/ic_note_eight.svg
    - packages/flutter_metronome/images/ic_note_quarter.svg
    - packages/flutter_metronome/images/ic_note_sixteenth.svg
    - packages/flutter_metronome/images/ic_note_triplet.svg
