name: flutter_metronome
description: A Metronome built in Flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_rust_bridge: ^1.54.0
  flutter_svg: ^1.1.6
  soundpool: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    # TODO: This is for whatever reason not working
    - packages/flutter_metronome/assets/sounds/default_metronome_up.wav
    - packages/flutter_metronome/assets/sounds/default_metronome.wav
    - packages/flutter_metronome/assets/images/ic_note_eight.svg
    - packages/flutter_metronome/assets/images/ic_note_quarter.svg
    - packages/flutter_metronome/assets/images/ic_note_sixteenth.svg
    - packages/flutter_metronome/assets/images/ic_note_triplet.svg
